version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: sgv-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: sgv_database
    ports:
      - "5432:5432"
    volumes:
      - sgv_pgdata:/var/lib/postgresql/data

volumes:
  sgv_pgdata: