import unicodedata


def normalize_text(value: str) -> str:
    cleaned = (value or "").strip().lower()
    normalized = unicodedata.normalize("NFD", cleaned)
    return "".join(char for char in normalized if unicodedata.category(char) != "Mn")


PRODUCT_RULES = [
    {
        "departments": ["Mercearia"],
        "products": ["arroz"],
        "types": ["Branco Tipo 1", "Parboilizado", "Integral", "Agulhinha", "Jasmim"],
        "sizes": ["1KG", "2KG", "5KG"],
        "default_package_name": "FARDO",
        "default_package_units": 30,
    },
    {
        "departments": ["Mercearia"],
        "products": ["feijao"],
        "types": ["Carioca", "Preto", "Fradinho", "Branco", "Rajado"],
        "sizes": ["1KG", "2KG"],
        "default_package_name": "FARDO",
        "default_package_units": 30,
    },
    {
        "departments": ["Mercearia"],
        "products": ["acucar"],
        "types": ["Cristal", "Refinado", "Mascavo", "Demerara"],
        "sizes": ["1KG", "2KG", "5KG"],
        "default_package_name": "FARDO",
        "default_package_units": 10,
    },
    {
        "departments": ["Mercearia"],
        "products": ["oleo", "oleo de soja"],
        "types": ["Soja", "Canola", "Girassol", "Milho"],
        "sizes": ["900ML", "1L", "5L"],
        "default_package_name": "CAIXA",
        "default_package_units": 20,
    },
    {
        "departments": ["Mercearia"],
        "products": ["macarrao"],
        "types": ["Espaguete", "Parafuso", "Penne", "Talharim"],
        "sizes": ["500G", "1KG"],
        "default_package_name": "FARDO",
        "default_package_units": 20,
    },
    {
        "departments": ["Laticinios", "Bebidas"],
        "products": ["leite"],
        "types": ["Integral", "Desnatado", "Semidesnatado", "Zero Lactose"],
        "sizes": ["200ML", "1L", "2L"],
        "default_package_name": "CAIXA",
        "default_package_units": 12,
    },
    {
        "departments": ["Laticinios"],
        "products": ["iogurte"],
        "types": ["Natural", "Morango", "Grego", "Desnatado"],
        "sizes": ["170G", "500G", "1KG"],
        "default_package_name": "CAIXA",
        "default_package_units": 24,
    },
    {
        "departments": ["Laticinios"],
        "products": ["queijo"],
        "types": ["Mussarela", "Prato", "Minas", "Parmesao", "Coalho"],
        "sizes": ["200G", "500G", "1KG", "3KG"],
        "default_package_name": "CAIXA",
        "default_package_units": 8,
    },
    {
        "departments": ["Bebidas"],
        "products": ["refrigerante", "refri"],
        "types": ["Cola", "Guarana", "Laranja", "Limao", "Uva", "Zero"],
        "sizes": ["200ML", "350ML", "600ML", "1L", "1.5L", "2L", "3L"],
        "default_package_name": "FARDO",
        "default_package_units": 6,
    },
    {
        "departments": ["Bebidas"],
        "products": ["suco"],
        "types": ["Uva", "Laranja", "Manga", "Maracuja", "Abacaxi", "Caju"],
        "sizes": ["200ML", "1L", "1.5L", "2L"],
        "default_package_name": "CAIXA",
        "default_package_units": 12,
    },
    {
        "departments": ["Bebidas"],
        "products": ["agua"],
        "types": ["Sem Gas", "Com Gas", "Saborizada"],
        "sizes": ["500ML", "1L", "1.5L", "2L", "5L"],
        "default_package_name": "FARDO",
        "default_package_units": 12,
    },
    {
        "departments": ["Bebidas"],
        "products": ["cerveja"],
        "types": ["Pilsen", "Puro Malte", "Lager", "Sem Alcool"],
        "sizes": ["269ML", "350ML", "473ML", "600ML"],
        "default_package_name": "CAIXA",
        "default_package_units": 12,
    },
    {
        "departments": ["Doces"],
        "products": ["chocolate"],
        "types": ["Ao Leite", "Meio Amargo", "Branco", "Recheado"],
        "sizes": ["80G", "90G", "100G", "1KG"],
        "default_package_name": "CAIXA",
        "default_package_units": 24,
    },
    {
        "departments": ["Doces"],
        "products": ["biscoito recheado"],
        "types": ["Chocolate", "Morango", "Baunilha"],
        "sizes": ["90G", "120G", "140G"],
        "default_package_name": "CAIXA",
        "default_package_units": 40,
    },
    {
        "departments": ["Doces"],
        "products": ["bala"],
        "types": ["Mastigavel", "Dura", "Halls", "Goma"],
        "sizes": ["100G", "500G", "1KG"],
        "default_package_name": "PACOTE",
        "default_package_units": 1,
    },
    {
        "departments": ["Higiene Pessoal", "Higiene"],
        "products": ["sabonete"],
        "types": ["Em Barra", "Liquido", "Glicerina", "Antibacteriano"],
        "sizes": ["85G", "90G", "250ML"],
        "default_package_name": "CAIXA",
        "default_package_units": 12,
    },
    {
        "departments": ["Higiene Pessoal", "Higiene"],
        "products": ["shampoo"],
        "types": ["Hidratacao", "Anticaspa", "Infantil", "Reconstrucao"],
        "sizes": ["200ML", "350ML", "400ML"],
        "default_package_name": "CAIXA",
        "default_package_units": 12,
    },
    {
        "departments": ["Higiene Pessoal", "Higiene"],
        "products": ["desodorante"],
        "types": ["Aerosol", "Roll-On", "Creme", "Sem Perfume"],
        "sizes": ["50ML", "90G", "150ML"],
        "default_package_name": "CAIXA",
        "default_package_units": 12,
    },
    {
        "departments": ["Higiene Pessoal", "Higiene"],
        "products": ["creme dental"],
        "types": ["Branqueador", "Anticaries", "Sensibilidade", "Infantil"],
        "sizes": ["70G", "90G", "180G"],
        "default_package_name": "CAIXA",
        "default_package_units": 12,
    },
    {
        "departments": ["Carnes"],
        "products": ["frango"],
        "types": [
            "Peito",
            "Coxa",
            "Sobrecoxa",
            "Asa",
            "Filezinho",
            "Coracao",
            "Moela",
            "Inteiro",
        ],
        "sizes": ["500G", "1KG", "2KG", "5KG"],
        "default_package_name": "CAIXA",
        "default_package_units": 10,
    },
    {
        "departments": ["Carnes"],
        "products": ["carne bovina", "bovina"],
        "types": [
            "Acem",
            "Patinho",
            "Alcatra",
            "Picanha",
            "Coxao Mole",
            "Coxao Duro",
            "Fraldinha",
            "Musculo",
            "Costela",
        ],
        "sizes": ["500G", "1KG", "2KG", "5KG", "10KG"],
        "default_package_name": "CAIXA",
        "default_package_units": 8,
    },
    {
        "departments": ["Carnes"],
        "products": ["carne suina", "suina", "suino"],
        "types": ["Lombo", "Pernil", "Costela", "Bisteca", "Copa Lombo", "Barriga"],
        "sizes": ["500G", "1KG", "2KG", "5KG"],
        "default_package_name": "CAIXA",
        "default_package_units": 8,
    },
    {
        "departments": ["Carnes"],
        "products": ["peixe"],
        "types": ["Tilapia", "Merluza", "Sardinha", "Atum", "Pescada", "File"],
        "sizes": ["500G", "1KG", "2KG"],
        "default_package_name": "CAIXA",
        "default_package_units": 10,
    },
    {
        "departments": ["Carnes"],
        "products": ["linguica", "calabresa"],
        "types": ["Toscana", "Calabresa", "Frango", "Suina", "Defumada"],
        "sizes": ["400G", "500G", "1KG", "2KG"],
        "default_package_name": "CAIXA",
        "default_package_units": 12,
    },
    {
        "departments": ["Mercearia"],
        "products": [],
        "types": ["Tradicional"],
        "sizes": ["500G", "1KG", "2KG", "5KG"],
        "default_package_name": "FARDO",
        "default_package_units": 10,
    },
    {
        "departments": ["Laticinios"],
        "products": [],
        "types": ["Tradicional", "Integral", "Desnatado"],
        "sizes": ["170G", "500G", "1L", "2L"],
        "default_package_name": "CAIXA",
        "default_package_units": 12,
    },
    {
        "departments": ["Bebidas"],
        "products": [],
        "types": ["Tradicional", "Zero", "Sem Gas", "Com Gas"],
        "sizes": ["200ML", "350ML", "600ML", "1L", "2L"],
        "default_package_name": "FARDO",
        "default_package_units": 6,
    },
    {
        "departments": ["Carnes"],
        "products": [],
        "types": ["Bovina", "Suina", "Frango", "Peixe"],
        "sizes": ["500G", "1KG", "2KG", "5KG"],
        "default_package_name": "CAIXA",
        "default_package_units": 8,
    },
    {
        "departments": ["Doces"],
        "products": [],
        "types": ["Tradicional", "Diet", "Zero Acucar"],
        "sizes": ["30G", "80G", "100G", "500G", "1KG"],
        "default_package_name": "CAIXA",
        "default_package_units": 24,
    },
    {
        "departments": ["Higiene Pessoal", "Higiene"],
        "products": [],
        "types": ["Tradicional", "Infantil", "Sensitive", "Premium"],
        "sizes": ["70G", "90G", "200ML", "350ML"],
        "default_package_name": "CAIXA",
        "default_package_units": 12,
    },
]


LOCAL_CATALOG_ITEMS = [
    {
        "barcode": "7891000053508",
        "product_name": "Arroz",
        "brand": "Camil",
        "category": "Massas e Graos",
        "variant_label": "Branco Tipo 1",
        "package_size": "5KG",
        "department_names": ["Mercearia"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7891000053515",
        "product_name": "Arroz",
        "brand": "Camil",
        "category": "Massas e Graos",
        "variant_label": "Parboilizado",
        "package_size": "5KG",
        "department_names": ["Mercearia"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7891000053522",
        "product_name": "Arroz",
        "brand": "Camil",
        "category": "Massas e Graos",
        "variant_label": "Integral",
        "package_size": "1KG",
        "department_names": ["Mercearia"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7896006710015",
        "product_name": "Arroz",
        "brand": "Tio Joao",
        "category": "Massas e Graos",
        "variant_label": "Branco Tipo 1",
        "package_size": "5KG",
        "department_names": ["Mercearia"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7896006710022",
        "product_name": "Arroz",
        "brand": "Tio Joao",
        "category": "Massas e Graos",
        "variant_label": "Integral",
        "package_size": "1KG",
        "department_names": ["Mercearia"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7894900019018",
        "product_name": "Arroz",
        "brand": "Prato Fino",
        "category": "Massas e Graos",
        "variant_label": "Branco Tipo 1",
        "package_size": "5KG",
        "department_names": ["Mercearia"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7894900019025",
        "product_name": "Arroz",
        "brand": "Prato Fino",
        "category": "Massas e Graos",
        "variant_label": "Integral",
        "package_size": "1KG",
        "department_names": ["Mercearia"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7891910012343",
        "product_name": "Arroz",
        "brand": "Uniao",
        "category": "Massas e Graos",
        "variant_label": "Branco Tipo 1",
        "package_size": "1KG",
        "department_names": ["Mercearia"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7896004400918",
        "product_name": "Feijao",
        "brand": "Kicaldo",
        "category": "Massas e Graos",
        "variant_label": "Carioca",
        "package_size": "1KG",
        "department_names": ["Mercearia"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7896110005144",
        "product_name": "Acucar",
        "brand": "Uniao",
        "category": "Mercearia",
        "variant_label": "Refinado",
        "package_size": "1KG",
        "department_names": ["Mercearia"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7891150035409",
        "product_name": "Leite",
        "brand": "Italac",
        "category": "Laticinios",
        "variant_label": "Integral",
        "package_size": "1L",
        "department_names": ["Laticinios", "Bebidas"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7894900011517",
        "product_name": "Iogurte",
        "brand": "Vigor",
        "category": "Laticinios",
        "variant_label": "Morango",
        "package_size": "170G",
        "department_names": ["Laticinios"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7894900701517",
        "product_name": "Queijo",
        "brand": "Tirolez",
        "category": "Laticinios",
        "variant_label": "Mussarela",
        "package_size": "500G",
        "department_names": ["Laticinios"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7894900911512",
        "product_name": "Refrigerante",
        "brand": "Coca-Cola",
        "category": "Bebidas",
        "variant_label": "Cola",
        "package_size": "2L",
        "department_names": ["Bebidas"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7892840813017",
        "product_name": "Refrigerante",
        "brand": "Guarana Antarctica",
        "category": "Bebidas",
        "variant_label": "Guarana",
        "package_size": "2L",
        "department_names": ["Bebidas"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7894900530001",
        "product_name": "Suco",
        "brand": "Del Valle",
        "category": "Bebidas",
        "variant_label": "Laranja",
        "package_size": "1L",
        "department_names": ["Bebidas"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7890000011223",
        "product_name": "Agua",
        "brand": "Minalba",
        "category": "Bebidas",
        "variant_label": "Sem Gas",
        "package_size": "1.5L",
        "department_names": ["Bebidas"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7891991000838",
        "product_name": "Cerveja",
        "brand": "Skol",
        "category": "Bebidas",
        "variant_label": "Pilsen",
        "package_size": "350ML",
        "department_names": ["Bebidas"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7891515982214",
        "product_name": "Frango",
        "brand": "Sadia",
        "category": "Carnes e Aves",
        "variant_label": "Peito",
        "package_size": "1KG",
        "department_names": ["Carnes"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7891515982215",
        "product_name": "Frango",
        "brand": "Sadia",
        "category": "Carnes e Aves",
        "variant_label": "Coxa",
        "package_size": "1KG",
        "department_names": ["Carnes"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7891515982216",
        "product_name": "Frango",
        "brand": "Sadia",
        "category": "Carnes e Aves",
        "variant_label": "Sobrecoxa",
        "package_size": "1KG",
        "department_names": ["Carnes"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7891515982217",
        "product_name": "Frango",
        "brand": "Sadia",
        "category": "Carnes e Aves",
        "variant_label": "Asa",
        "package_size": "1KG",
        "department_names": ["Carnes"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7891149010011",
        "product_name": "Carne Bovina",
        "brand": "Friboi",
        "category": "Carnes e Aves",
        "variant_label": "Acem",
        "package_size": "1KG",
        "department_names": ["Carnes"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7891149010012",
        "product_name": "Carne Bovina",
        "brand": "Friboi",
        "category": "Carnes e Aves",
        "variant_label": "Patinho",
        "package_size": "1KG",
        "department_names": ["Carnes"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7891149010013",
        "product_name": "Carne Bovina",
        "brand": "Friboi",
        "category": "Carnes e Aves",
        "variant_label": "Picanha",
        "package_size": "1KG",
        "department_names": ["Carnes"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7891149010014",
        "product_name": "Carne Suina",
        "brand": "Seara",
        "category": "Carnes e Aves",
        "variant_label": "Lombo",
        "package_size": "1KG",
        "department_names": ["Carnes"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7891149010015",
        "product_name": "Carne Suina",
        "brand": "Seara",
        "category": "Carnes e Aves",
        "variant_label": "Pernil",
        "package_size": "1KG",
        "department_names": ["Carnes"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7891149010016",
        "product_name": "Peixe",
        "brand": "Copacol",
        "category": "Carnes e Aves",
        "variant_label": "Tilapia",
        "package_size": "1KG",
        "department_names": ["Carnes"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7891149010017",
        "product_name": "Linguica",
        "brand": "Perdigao",
        "category": "Carnes e Aves",
        "variant_label": "Toscana",
        "package_size": "1KG",
        "department_names": ["Carnes"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7891000100103",
        "product_name": "Chocolate",
        "brand": "Lacta",
        "category": "Doces e Biscoitos",
        "variant_label": "Ao Leite",
        "package_size": "90G",
        "department_names": ["Doces"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7891000100110",
        "product_name": "Chocolate",
        "brand": "Nestle",
        "category": "Doces e Biscoitos",
        "variant_label": "Meio Amargo",
        "package_size": "90G",
        "department_names": ["Doces"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7891000100127",
        "product_name": "Biscoito Recheado",
        "brand": "Oreo",
        "category": "Doces e Biscoitos",
        "variant_label": "Chocolate",
        "package_size": "90G",
        "department_names": ["Doces"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7891000100134",
        "product_name": "Bala",
        "brand": "Halls",
        "category": "Doces e Biscoitos",
        "variant_label": "Menta",
        "package_size": "28G",
        "department_names": ["Doces"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7891000100202",
        "product_name": "Sabonete",
        "brand": "Dove",
        "category": "Higiene Pessoal",
        "variant_label": "Em Barra",
        "package_size": "90G",
        "department_names": ["Higiene Pessoal", "Higiene"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7891000100219",
        "product_name": "Shampoo",
        "brand": "Pantene",
        "category": "Higiene Pessoal",
        "variant_label": "Hidratacao",
        "package_size": "350ML",
        "department_names": ["Higiene Pessoal", "Higiene"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7891000100226",
        "product_name": "Desodorante",
        "brand": "Rexona",
        "category": "Higiene Pessoal",
        "variant_label": "Aerosol",
        "package_size": "150ML",
        "department_names": ["Higiene Pessoal", "Higiene"],
        "source": "catalogo_local_br",
    },
    {
        "barcode": "7891000100233",
        "product_name": "Creme Dental",
        "brand": "Colgate",
        "category": "Higiene Pessoal",
        "variant_label": "Anticaries",
        "package_size": "90G",
        "department_names": ["Higiene Pessoal", "Higiene"],
        "source": "catalogo_local_br",
    },
]


def get_local_product_rules() -> list[dict]:
    return PRODUCT_RULES.copy()


def search_local_catalog(query: str, department: str = "", limit: int = 20) -> list[dict]:
    term = normalize_text(query)
    dep = normalize_text(department)
    if len(term) < 2:
        return []

    results = []
    for item in LOCAL_CATALOG_ITEMS:
        haystack = normalize_text(
            " ".join(
                [
                    item.get("product_name", ""),
                    item.get("brand", ""),
                    item.get("category", ""),
                    item.get("variant_label", ""),
                ]
            )
        )
        if term not in haystack:
            continue
        if dep:
            item_deps = [normalize_text(name) for name in item.get("department_names", [])]
            if dep not in item_deps:
                continue
        results.append(item)
        if len(results) >= limit:
            break
    return results


def lookup_local_by_barcode(barcode: str) -> dict | None:
    code = "".join(char for char in (barcode or "") if char.isdigit())
    if not code:
        return None
    for item in LOCAL_CATALOG_ITEMS:
        if item.get("barcode") == code:
            return item
    return None


