# Generated by Django 6.0.3 on 2026-03-20 17:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_productpackage_stockmovement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='productbase',
            options={'ordering': ['name', 'brand'], 'verbose_name': 'produto base', 'verbose_name_plural': 'produtos base'},
        ),
        migrations.AlterModelOptions(
            name='productpackage',
            options={'ordering': ['units_per_package', 'name'], 'verbose_name': 'embalagem do item', 'verbose_name_plural': 'embalagens dos itens'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['-updated_at'], 'verbose_name': 'item de estoque', 'verbose_name_plural': 'itens de estoque'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'movimentacao de estoque', 'verbose_name_plural': 'movimentacoes de estoque'},
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='brand',
            field=models.CharField(max_length=120, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.category', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='name',
            field=models.CharField(max_length=120, verbose_name='produto'),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='productpackage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='productpackage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='productpackage',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='padrao'),
        ),
        migrations.AlterField(
            model_name='productpackage',
            name='name',
            field=models.CharField(max_length=40, verbose_name='embalagem'),
        ),
        migrations.AlterField(
            model_name='productpackage',
            name='units_per_package',
            field=models.PositiveIntegerField(default=1, verbose_name='unidades por embalagem'),
        ),
        migrations.AlterField(
            model_name='productpackage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='productpackage',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='api.productvariant', verbose_name='item'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='package_size',
            field=models.CharField(max_length=30, verbose_name='tamanho'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preco'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.productbase', verbose_name='produto base'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='estoque (unidades)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant_label',
            field=models.CharField(blank=True, max_length=80, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('RECEIVE', 'Recebimento'), ('SELL', 'Venda'), ('ADJUST', 'Ajuste'), ('LOSS', 'Perda'), ('RETURN', 'Devolucao')], max_length=12, verbose_name='tipo de movimentacao'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='observacao'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='api.productpackage', verbose_name='embalagem'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='package_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='quantidade de embalagens'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='units_delta',
            field=models.IntegerField(verbose_name='variacao em unidades'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='api.productvariant', verbose_name='item'),
        ),
    ]
