# Generated by Django 6.0.3 on 2026-03-26 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_department_productbase_departments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='category_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_active'], name='department_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='productbase',
            index=models.Index(fields=['name'], name='product_base_name_idx'),
        ),
        migrations.AddIndex(
            model_name='productbase',
            index=models.Index(fields=['brand'], name='product_base_brand_idx'),
        ),
        migrations.AddIndex(
            model_name='productbase',
            index=models.Index(fields=['is_active'], name='product_base_active_idx'),
        ),
        migrations.AddIndex(
            model_name='productpackage',
            index=models.Index(fields=['variant', 'is_active'], name='package_variant_active_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['is_active'], name='variant_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['stock'], name='variant_stock_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['updated_at'], name='variant_updated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active'], name='variant_product_active_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['created_at'], name='movement_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['variant', 'created_at'], name='movement_variant_created_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'created_at'], name='movement_type_created_idx'),
        ),
    ]
