# Generated by Django 6.0.3 on 2026-04-17 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_productvariant_variant_active_updated_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('expense_type', models.CharField(choices=[('FIXA', 'Fixa'), ('VARIAVEL', 'Variável')], max_length=10, verbose_name='tipo')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'despesa',
                'verbose_name_plural': 'despesas',
                'ordering': ['-date'],
            },
        ),
    ]
