"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
FRONTEND_DIST_DIR = BASE_DIR / "frontend" / "dist"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7ru&$txfi$w39=y5)g#8z8so2lbj46l^81r0d*wey1(s++4rde'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "localhost"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [FRONTEND_DIST_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

def _as_int(name, default):
    try:
        return int(os.getenv(name, str(default)))
    except (TypeError, ValueError):
        return default


def _as_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return str(value).strip().lower() in {"1", "true", "yes", "on"}


DB_BACKEND = os.getenv("DB_BACKEND", "sqlite").strip().lower()
DB_CONN_MAX_AGE = _as_int("DB_CONN_MAX_AGE", 120)
DB_ATOMIC_REQUESTS = _as_bool("DB_ATOMIC_REQUESTS", True)

if DB_BACKEND in {"postgres", "postgresql", "pg"}:
    db_name = os.getenv("DB_NAME", "mercado")
    db_user = os.getenv("DB_USER", "postgres")
    db_password = os.getenv("DB_PASSWORD", "")
    db_host = os.getenv("DB_HOST", "127.0.0.1")
    db_port = _as_int("DB_PORT", 5432)
    db_sslmode = os.getenv("DB_SSLMODE", "prefer")
    db_connect_timeout = _as_int("DB_CONNECT_TIMEOUT", 10)
    db_statement_timeout_ms = _as_int("DB_STATEMENT_TIMEOUT_MS", 12000)
    db_lock_timeout_ms = _as_int("DB_LOCK_TIMEOUT_MS", 5000)
    db_idle_tx_timeout_ms = _as_int("DB_IDLE_IN_TX_TIMEOUT_MS", 30000)
    db_app_name = os.getenv("DB_APP_NAME", "mercado-api")
    db_timezone = os.getenv("DB_TIMEZONE", "America/Sao_Paulo")

    pg_options = (
        f"-c statement_timeout={db_statement_timeout_ms} "
        f"-c lock_timeout={db_lock_timeout_ms} "
        f"-c idle_in_transaction_session_timeout={db_idle_tx_timeout_ms} "
        f"-c timezone={db_timezone}"
    )

    default_db = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": db_name,
        "USER": db_user,
        "PASSWORD": db_password,
        "HOST": db_host,
        "PORT": db_port,
        "CONN_MAX_AGE": DB_CONN_MAX_AGE,
        "CONN_HEALTH_CHECKS": True,
        "ATOMIC_REQUESTS": DB_ATOMIC_REQUESTS,
        "DISABLE_SERVER_SIDE_CURSORS": _as_bool("DB_DISABLE_SERVER_SIDE_CURSORS", False),
        "OPTIONS": {
            "connect_timeout": db_connect_timeout,
            "sslmode": db_sslmode,
            "application_name": db_app_name,
            "options": pg_options,
        },
    }

    # Django 5.1+ / 6.x with psycopg can use built-in pooling.
    if _as_bool("DB_POOL_ENABLED", True):
        default_db["OPTIONS"]["pool"] = {
            "min_size": _as_int("DB_POOL_MIN_SIZE", 4),
            "max_size": _as_int("DB_POOL_MAX_SIZE", 40),
            "timeout": _as_int("DB_POOL_TIMEOUT", 30),
        }

    DATABASES = {"default": default_db}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
            "CONN_MAX_AGE": DB_CONN_MAX_AGE,
            "ATOMIC_REQUESTS": DB_ATOMIC_REQUESTS,
            "OPTIONS": {
                "timeout": _as_int("DB_SQLITE_TIMEOUT", 30),
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# Frontend React (Vite) em desenvolvimento.
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]


REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer'],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}


BLUESOFT_COSMOS_TOKEN = os.getenv("BLUESOFT_COSMOS_TOKEN", "")
BLUESOFT_COSMOS_USER_AGENT = os.getenv("BLUESOFT_COSMOS_USER_AGENT", "")
